import test from 'node:test';
import assert from 'node:assert/strict';
import { LocalCameraPreview } from '../call-consent.js';
import { AgentOrchestrator } from '../orchestrator.js';
import { ConversationStateMachine } from '../state-machine.js';
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return{resolve,promise};};
function cameraFixture(get){const track={stopped:false,stop(){this.stopped=true;},addEventListener(){}};const stream={getTracks:()=>[track],getVideoTracks:()=>[track]};let constraints;const camera=new LocalCameraPreview({mediaDevices:{getUserMedia:async c=>{constraints=c;return get?get.promise:stream;}}});return{camera,track,stream,constraints:()=>constraints};}
test('construction never requests camera',()=>{const f=cameraFixture();assert.equal(f.constraints(),undefined);});
test('camera requests video only, never microphone',async()=>{const f=cameraFixture();assert.equal(await f.camera.open(),true);assert.equal(f.constraints().audio,false);assert.deepEqual(f.constraints().video,{facingMode:'user'});f.camera.stop();});
test('stop releases tracks and forgets stream',async()=>{const f=cameraFixture();await f.camera.open();f.camera.stop();assert.ok(f.track.stopped);assert.equal(f.camera.stream,null);});
test('late permission after close immediately releases device',async()=>{const wait=deferred();const f=cameraFixture(wait);const p=f.camera.open();f.camera.stop();wait.resolve(f.stream);assert.equal(await p,false);assert.ok(f.track.stopped);assert.equal(f.camera.stream,null);});
test('denied camera does not retain a stream',async()=>{const c=new LocalCameraPreview({mediaDevices:{getUserMedia:async()=>{throw Error('denied');}}});await assert.rejects(c.open());assert.equal(c.stream,null);});
function engine({connect,greet,respond}={}){const stats={stt:0,tts:0,disconnect:0,stopTts:0};const providers={avatar:{connect:connect||(async()=>{}),disconnect:async()=>{stats.disconnect++;},stopSpeaking(){},setEmotion(){},setListening(){},speak:async handle=>{await handle?.done;}},stt:{isSupported:()=>true,start:()=>{stats.stt++;},stop(){}},tts:{speak:()=>{stats.tts++;return{done:Promise.resolve(),stop:()=>{stats.stopTts++;}};}},llm:{greet,respond:respond||(async()=>({replyText:'Test reply'}))}};const orchestrator=new AgentOrchestrator({providers,stateMachine:new ConversationStateMachine(),agentIdentity:{},lang:'tr',autoListen:false});return{orchestrator,stats};}
test('language switch never opens unconsented microphone',async()=>{const f=engine();await f.orchestrator.start();await f.orchestrator.setLanguage('en');assert.equal(f.stats.stt,0);f.orchestrator.beginListening();assert.equal(f.stats.stt,1);await f.orchestrator.stop();await f.orchestrator.setLanguage('tr');assert.equal(f.stats.stt,1);});
test('closing while provider connects prevents greeting/TTS',async()=>{const wait=deferred();const f=engine({connect:()=>wait.promise,greet:async()=>({replyText:'Hello'})});const start=f.orchestrator.start();await f.orchestrator.stop();wait.resolve();await start;assert.equal(f.stats.tts,0);assert.ok(f.stats.disconnect>=1);});
test('closing during a pending greeting prevents speech',async()=>{const wait=deferred();const entered=deferred();const f=engine({greet:()=>{entered.resolve();return wait.promise;}});const start=f.orchestrator.start();await entered.promise;await f.orchestrator.stop();wait.resolve({replyText:'Hello'});await start;assert.equal(f.stats.tts,0);});
test('stop cancels the active speech handle',async()=>{const f=engine();let stopped=0;f.orchestrator._activeTts={stop:()=>{stopped++;}};await f.orchestrator.stop();assert.equal(stopped,1);assert.equal(f.orchestrator._activeTts,null);});
test('closing during LLM response prevents late speech',async()=>{const wait=deferred();const entered=deferred();const f=engine({respond:()=>{entered.resolve();return wait.promise;}});await f.orchestrator.start();f.orchestrator.beginListening();const response=f.orchestrator._handleCustomerUtterance('Test');await entered.promise;await f.orchestrator.stop();wait.resolve({replyText:'Late reply'});await response;assert.equal(f.stats.tts,0);});
